management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
          - info

  metrics:
    tags:
      application: tcoding-demo