spring:
  mail:
    host: smtp.163.com
    username: --@163.com
    password: --


    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory

    port: 465
    protocol: smtp
    default-encoding: UTF-8
