#CAS\u670D\u52A1\u5730\u5740
cas:
  server:
    host:
      url: http://localhost:8443/cas
      login_url: ${cas.server.host.url}/login
      #CAS\u670D\u52A1\u767B\u51FA\u5730\u5740
      logout_url: ${cas.server.host.url}/logout?service=${app.server.host.url}
app:
  server:
    host:
      url: http://localhost
  login:
    url: /login
  logout:
    url: /logout
server:
  port: 80
