server:
  servlet:
    context-path: tcoding
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/hello_spring_boot?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-test-query: "select 1"
      max-lifetime: 1800000
      connection-timeout: 3000
      pool-name: "DatebookHikariCP"
mybatis:
  #classpath\u548Cclasspath*\u533A\u522B\uFF1A
  #classpath\uFF1A\u53EA\u4F1A\u5230\u4F60\u7684class\u8DEF\u5F84\u4E2D\u67E5\u627E\u627E\u6587\u4EF6\u3002
  #classpath*\uFF1A\u4E0D\u4EC5\u5305\u542Bclass\u8DEF\u5F84\uFF0C\u8FD8\u5305\u62ECjar\u6587\u4EF6\u4E2D\uFF08class\u8DEF\u5F84\uFF09\u8FDB\u884C\u67E5\u627E\u3002
  #\u6CE8\u610F\uFF1A \u7528classpath*:\u9700\u8981\u904D\u5386\u6240\u6709\u7684classpath\uFF0C\u6240\u4EE5\u52A0\u8F7D\u901F\u5EA6\u662F\u5F88\u6162\u7684\uFF1B\u56E0\u6B64\uFF0C\u5728\u89C4\u5212\u7684\u65F6\u5019\uFF0C\u5E94\u8BE5\u5C3D\u53EF\u80FD\u89C4\u5212\u597D\u8D44\u6E90\u6587\u4EF6\u6240\u5728\u7684\u8DEF\u5F84\uFF0C\u5C3D\u91CF\u907F\u514D\u4F7F\u7528classpath*\u3002
  mapper-locations: classpath:mapper/**/*.xml
  type-handlers-package: com.tcoding.demo.mybatis.mbg.handler